InitialTask3/Models/ErrorViewModel.cs
namespace InitialTask3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InitialTask3/Models/Initial3Context.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace InitialTask3.Models;

public partial class Initial3Context : DbContext
{
    public Initial3Context()
    {
    }

    public Initial3Context(DbContextOptions<Initial3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Salary> Salaries { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=HRAVADA-L-5510\\SQLEXPRESS;Initial Catalog=Initial3;User ID=sa;Password=Welcome2evoke@1234; Trust Server Certificate=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Salary>(entity =>
        {
            entity.HasKey(e => e.ActualAnnualSalary);

            entity.ToTable("Salary");

            entity.Property(e => e.ActualAnnualSalary).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

InitialTask3/Models/Salary.cs
using System;
using System.Collections.Generic;

namespace InitialTask3.Models;

public partial class Salary
{
    public long ActualAnnualSalary { get; set; }

    public long? LastYearOtherIncome { get; set; }

    public long? TotalIncome { get; set; }
}

InitialTask3/Controllers/HomeController.cs
using InitialTask3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InitialTask3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private string _name = "Start Survey";
 

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
           
        }

        public IActionResult Index()
        {
            if (TempData["name"] == null) 
               TempData["name"] = "Start Survey";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InitialTask3/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InitialTask3.Models;

namespace InitialTask3.Controllers
{
    public class SalariesController : Controller
    {
        private readonly Initial3Context _context;

       
        public SalariesController(Initial3Context context)
        {
            _context = context;
        }

        // GET: Salaries
        public async Task<IActionResult> Index()

        {
           
              return _context.Salaries != null ? 
                          View(await _context.Salaries.ToListAsync()) :
                          Problem("Entity set 'Initial3Context.Salaries'  is null.");
        }

        // GET: Salaries/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Salaries == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries
                .FirstOrDefaultAsync(m => m.ActualAnnualSalary == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // GET: Salaries/Create
        public IActionResult Create()
        {
            TempData["name"] = "Update Survey";
            return View();
        }

        // POST: Salaries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActualAnnualSalary,LastYearOtherIncome,TotalIncome")] List<Salary> salary)
        {
          
      
            if (ModelState.IsValid)
            {
                _context.AddRange(salary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(salary);
        }

        // GET: Salaries/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Salaries == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries.FindAsync(id);
            if (salary == null)
            {
                return NotFound();
            }
            return View(salary);
        }

        // POST: Salaries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ActualAnnualSalary,LastYearOtherIncome,TotalIncome")] Salary salary)
        {
            if (id != salary.ActualAnnualSalary)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryExists(salary.ActualAnnualSalary))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(salary);
        }

        // GET: Salaries/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Salaries == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries
                .FirstOrDefaultAsync(m => m.ActualAnnualSalary == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // POST: Salaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Salaries == null)
            {
                return Problem("Entity set 'Initial3Context.Salaries'  is null.");
            }
            var salary = await _context.Salaries.FindAsync(id);
            if (salary != null)
            {
                _context.Salaries.Remove(salary);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryExists(long id)
        {
          return (_context.Salaries?.Any(e => e.ActualAnnualSalary == id)).GetValueOrDefault();
        }
    }
}

InitialTask3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <center>
   <button>


            <a class="nav-link text-dark" asp-area="" asp-controller="Salaries" asp-action="Create"  onclick="change()" >@TempData["name"]</a>

    </button>
    </center>
</div>

InitialTask3/Views/Salaries/Create.cshtml
@model InitialTask3.Models.Salary

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Salary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @TempData["name"]
         <table>
             <tr>
                   <th> </th>
                    <th>ActualAnnualSalary</th><br />
                    <th>LastYearOtherIncome</th><br />
                    <th>TotalIncome</th><br />
             </tr>
             <tr>
                 <td>Chief Executive Officer</td>
                    <td>
                        <div class="form-group">

                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
             </tr>
                <tr>
                    <td>General Manager</td>
                    <td>
                        <div class="form-group">

                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                     
                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Rooms Director</td>
                    <td>
                        <div class="form-group">
                   
                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Executive Administrative Assistant</td>
                    <td>
                        <div class="form-group">
                         
                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                           
                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Managing director</td>
                    <td>
                        <div class="form-group">

                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Area Genereal Manager</td>
                    <td>
                        <div class="form-group">

                            <input asp-for="ActualAnnualSalary" class="form-control" />
                            <span asp-validation-for="ActualAnnualSalary" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="LastYearOtherIncome" class="form-control" />
                            <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">

                            <input asp-for="TotalIncome" class="form-control" />
                            <span asp-validation-for="TotalIncome" class="text-danger"></span>
                        </div>
                    </td>
                </tr>








         </table>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InitialTask3/Views/Salaries/Delete.cshtml
@model InitialTask3.Models.Salary

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastYearOtherIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastYearOtherIncome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalIncome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ActualAnnualSalary" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InitialTask3/Views/Salaries/Details.cshtml
@model InitialTask3.Models.Salary

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Salary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastYearOtherIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastYearOtherIncome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalIncome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ActualAnnualSalary">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InitialTask3/Views/Salaries/Edit.cshtml
@model InitialTask3.Models.Salary

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Salary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ActualAnnualSalary" />
            <div class="form-group">
                <label asp-for="LastYearOtherIncome" class="control-label"></label>
                <input asp-for="LastYearOtherIncome" class="form-control" />
                <span asp-validation-for="LastYearOtherIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalIncome" class="control-label"></label>
                <input asp-for="TotalIncome" class="form-control" />
                <span asp-validation-for="TotalIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InitialTask3/Views/Salaries/Index.cshtml
@model IEnumerable<InitialTask3.Models.Salary>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LastYearOtherIncome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalIncome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastYearOtherIncome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalIncome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ActualAnnualSalary">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ActualAnnualSalary">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ActualAnnualSalary">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

InitialTask3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InitialTask3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InitialTask3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InitialTask3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                      
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InitialTask3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>